---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2 # or latest stable version
    hooks:
      - id: black
        name: Format Python code with Black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        name: Sort Python imports with isort
        args: [--profile=black]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.6 # check https://github.com/charliermarsh/ruff-pre-commit for latest
    hooks:
      - id: ruff
        name: Check with Ruff
        args: [--fix]
        pass_filenames: false
        always_run: true

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: Lint YAML files with yamllint
        args: [-d, relaxed]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        name: Format YAML files with Prettier
        types_or: [yaml]
        additional_dependencies:
          - prettier@3.0.3